### ISSUE TITLE
When opening a new tab, the app presents the same view.

### ISSUE THREAD

**Issue by jordanstudioroot** [tone-row/flowchart-fun#1]
*Problem:*
I opened a new tab because I wanted to have the sample instructions in one window while I played with the app in the other. When I did this, it duplicated my view in both tabs. Changes in one tab affected the other.

*Expected Result:*
Duplicate tabs running the app should be independent of each other.

*Preconditions:*
* As Of Commit:  33dca86bf6f6184cab54b33f3864a0bc7b966ea3
* Device: BOXX Desktop
* OS: Windows 10 Enterprise v2004
* Browser: Firefox
* Reproducibility: 100%

*Steps to Reproduce:*
1. Navigate to https://flowchart.fun/.
2. Right click the resultant tab.
3. Click "duplicate tab"
4. Make changes in the original tab.
5. Observe to see if those changes are reflected in the new tab.

*Notes:*
This issue also manifests if you open a new window or tab without the "duplicate tab" option and navigate to https://flowchart.fun/

This app is awesome! I have been looking for something like this for years! Thanks!

**Comment by rob-gordon** [comment]
I opted for keeping the current state of the textarea in window.localStorage - mainly because if people have written a bunch of lines and accidentally navigate away I wouldn't want them to lose their work.

For now, if you open an incognito window with the app you'll be able to see the instructions while you work on your flowchart

I'll leave this issue open for a bit to see if other people also find this behavior unexpected and if they do I'll work on a better solution.

Cheers!

**Comment by rob-gordon** [comment]
@jordanstudioroot Going to close this for now because I added the ability to [persist multiple pads at any url path](https://twitter.com/row_tone/status/1369712546643664898) last week. 

Hopefully that covers the case of working on multiple charts at once. Feel free to start a [discussion](https://github.com/tone-row/flowchart-fun/discussions) if you think that removing localStorage-persistence is still a better route to take.

Thanks!
