### ISSUE TITLE
Bug: Pressing tab with text selected overwrites selection & bypasses undo

### ISSUE THREAD

**Issue by jjkinsey** [tone-row/flowchart-fun#10]
Repro: enter text in the text area, select it, and press tab. Then, try using Undo to undo the change. The change will not be undoable.
Expected: Undo functions as usual.

Presumably this has something to do with how the tab functionality is implemented. Breaking undo is a bug, but I think it would be best if pressing tab with text selected indented each line of the selected text (trying this is how I discovered the issue).

**Comment by rob-gordon** [comment]
Thanks for flagging this. I really want to preserve undo functions for people so they don't lose their work. I'm going to temporarily roll back to before the tab functionality was done earlier today. It seems like the longer-term fix for this problem is to move from a textarea to a more robust javascript code editor (maybe something like CodeMirror) to support tabbing and other stuff.

**Comment by rob-gordon** [comment]
I'm going to close this with a reference to the discussion about migrating to a browser-based code editor
https://github.com/tone-row/flowchart-fun/discussions/45
