### ISSUE TITLE
Suggestion: eliminate all sandwich delimiters

### ISSUE THREAD

**Issue by breck7** [tone-row/flowchart-fun#102]
Despite the fact that >99% of programming languages use "sandwich delimiters" like quotes, brackets, parens, et cetera, I figured out they are never necessary, and it's pretty fun to get rid of them entirely:

Here are some examples: https://jtree.treenotation.org/designer/

For flowchart-fun, I suggest:

[1] Drop /* */ and replace with a "comment" block.

```
/*
or 
multiline 
comments

Have fun! 🎉
*/
```

Becomes:

```
comment
 or 
 multiline 
 comments
 
 Have fun! 🎉
```

For the 0.0001% edge case where someone wants to have a node that is just the text "comment", they can capitalize the "c" to "Comment" or switch to a different tool. Not a big deal.

For circular references, I'd maybe go with hashtags. #[int] would be the line number. ##[string] would be insert a custom node id. and #[string] would be a link to the named node.

```
this app works by typing
  ##linking you can link to nodes using their ID in parentheses
    like this: #1
    lines have a default ID of their line-number
      but you can also supply a custom ID in brackets
        like this: #linking
```

**Comment by rob-gordon** [comment]
Wow, that tree notation site is awesome! (albeit slightly over my head :)

This is an interesting idea, though I think some people would be unhappy if the flowcharts stored in their localStorage suddenly stopped working because the syntax had changed.

I'll leave this issue open in case other people agree and want to chime in.

Thanks for the suggestion!
