### ISSUE TITLE
Leaving root node blank breaks app

### ISSUE THREAD

**Issue by VictorioBerra** [tone-row/flowchart-fun#130]
![vG1Q8A0qD1](https://user-images.githubusercontent.com/2934507/118841346-de098f00-b88d-11eb-813c-1be049fe9225.gif)

1. Clear all text from root node
2. click around
3. Add text back, observe that the app is now broken

**Comment by rob-gordon** [comment]
Thank you for opening this! Sorry for not replying sooner. 

The app stops successfully rendering because even once you re-add text because there is a now invalid pointer on line 5 
`(This app works by typing)`

I've opened up a pull-request so that the graph no longer updates when invalid (what happens first when write `This ABC`), and also gives the user the minimum amount of feedback in the form of an error message saying `Text Invalid` 

In the future I hope to report to the user which line specifically is invalid.
