### ISSUE TITLE
Many nodes going to a single box

### ISSUE THREAD

**Issue by josephernest** [tone-row/flowchart-fun#21]
Hi, congrats for your tool!

In order to do something like "many nodes  go to 1 node":

![image](https://user-images.githubusercontent.com/6168083/109792948-590ac400-7c14-11eb-8ee5-c8cc868331c9.png)

is there a better way than doing:

    A
      container
    B
      (2)
    C
      (2)
    D
      (2)
    E
      (2)

to avoid the repetition of newlines with `(2)`?

**Comment by rob-gordon** [comment]
An alternative (though not more concise) is using an [id]. I just wanted to mention that because then if your lines shift you won't need to rewrite the line numbers.
```
A
 [container] container
B
 (container)
C
 (container)
D
 (container)
```

There is not, at present, any shorter way to write. I guess the syntax really favors more children over more parents (tree shapes) 😅

I don't want to add anything to the syntax without gathering more feedback so I'm going turn this issue into a discussion where people can show interest / suggest a syntax to accomplish this.
