### ISSUE TITLE
Working around cytoscape error messaging

### ISSUE THREAD

**Issue by ikesau** [tone-row/flowchart-fun#251]
EDIT: This was a misguided ticket that misunderstood the issue at hand. I now realize it's about parsing the error messages from a primary dependency of the project, cytoscape.js.

On MacOS Firefox Developer Edition 98.0b6

This bug causes the renderer to crash (but doesn't happen when the tutorial window is open)

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/11844404/155045887-f8a3cef3-c52b-4fb8-8f97-018e11433c69.png">
```

**Comment by ikesau** [comment]
After some more playing, this doesn't appear to be an issue when creating a new chart - only when adjusting the default example.

Also appears to be an issue in Chrome

**Comment by rob-gordon** [comment]
@ikesau You're getting an error because line 11 is expecting to find a target `1` – this will look for either a line with ID `[1]` ([like this](https://flowchart.fun/c#IYKA2gjAugBARiAxiGMAuB7AXDAFBASiA)) or a line with the label `1` ([like this](https://flowchart.fun/c#MwKATCCMIAwgBPALgewFzwBSQJRA)), or this node on the line number 1 ([like this](https://flowchart.fun/c#JYcgtgBA9gdhA2wYFMIEYBQpKwU1ATFuNHIihAMwYQQAuUAXBABRoCUQA)). In your case none of those three exist, so it's telling you it doesn't know which target node to draw the edge to.

**Comment by rob-gordon** [comment]
Let me know if that doesn't cover it or if the bug is related to the tutorial window.

**Comment by ikesau** [comment]
Oh god If only I'd actually read the example.  Sorry for the drive-by ticket. 🤦 

Two things then:
1. looks like cytoscape.js uses the french spelling of existent
2. The error message reads extremely "programmatically generated by some dependency" which is why I assumed it wasn't my fault 😅 - if we can't change their messaging, could we possibly add some "here's the culprit" line highlighting?

**Comment by rob-gordon** [comment]
> looks like cytoscape.js uses the french spelling of existent

I never caught that- weird!

I totally agree that we need some more human-readable error messages. I've made a task for myself and I'll leave this open until it merges.

Thanks!

**Comment by rob-gordon** [comment]
@ikesau Going to close this one because error messaging got a little improvement in the last cycle. https://twitter.com/tone_row_/status/1505931806469677063

Thanks for opening!
