### ISSUE TITLE
Object pinning

### ISSUE THREAD

**Issue by james-powis** [tone-row/flowchart-fun#34]
Scenario: Assume you draw out a large arbitrary number of boxes and connections. After initial keyboard bashing you clean up the automatically rendered output by dragging them into a better layout which makes more sense to you as a user than the computer. Except after 2 hours of work you realize you need to add one last shape and connection. Doing so causes the push strength to recalculate and all your hard work organizing disappear. You have to start all over.

Ideal solution: a toggle that freezes the existing shapes in place, new shapes would at best be placed and pushed away by previous shapes without the new shape pushing on those older "Frozen" shapes.

**Comment by rob-gordon** [comment]
I agree, persisting user-augmented layouts could be hugely beneficial, and the notion of pinning could work well. 

I need to do some tests to make sure it doesn't negatively impact the [layout engine](https://github.com/cytoscape/cytoscape.js-dagre). In other words, if we pin certain boxes, can we still reflow the layout intelligently around those pinned boxes.

My other concern is that, although we can store the pinning in-memory (like while the user is using the site), will it be confusing for users if they  refresh (or open another tab) and their graph loses the layout. Which then leads me to think... should we search for a solution to pinning _via_ the syntax so that we can persist it :\ 

A lot to think about but I will leave this issue open so everyone can make suggestions.

Thanks for opening this one!

**Comment by mristin** [comment]
Maybe it would make sense to import/export the pinning in a separate file? This way you would separate the graph definition (the text that the user sees and types) and the properties of the nodes and edges. An explicit import/export would help with refreshes as well.

Perhaps this can also be the solution to #97? The user clicks on a node or an edge. A separate menu shows where you can change color, shape, change text properties (fonts, size *etc.*).

**Comment by physics515** [comment]
What if there was just a boolean value in the header to disable auto-regeneration of the layout.

for example:

```
~~~
layout:
  name: cose
  rankDir: LR
  auto-regen: false
~~~
```

When set to false any new nodes would be either placed relative to their parent node (ex. Right: 100px, Down: 100px) or in the center of the current view, if no parent exists. When set to true, it acts as it does currently.

**Comment by rob-gordon** [comment]
@james-powis 

> Ideal solution: a toggle that freezes the existing shapes in place, new shapes would at best be placed and pushed away by previous shapes without the new shape pushing on those older "Frozen" shapes.

True frozen graphs are now possible. Thanks for suggesting this way back!

https://user-images.githubusercontent.com/159949/172648574-cd3efbf4-2b91-44c0-950e-444a2b6549df.mov
