### ISSUE TITLE
Link to container children breaks if id > 3 characters

### ISSUE THREAD

**Issue by iotasquared** [tone-row/flowchart-fun#512]
This config:

inventory_item .red  {
name 
    set: (#a)
}

create_inventory_item  .blue   #abc {
item_name  #a
}

Works as expected
![image](https://github.com/tone-row/flowchart-fun/assets/526758/ad621962-70b4-4fd4-b110-e09e0a72db3a)

Changing the id of the second container to #abcd no longer renders the edge

inventory_item .red  {
name 
    set: (#a)
}

create_inventory_item  .blue   #abcd {
item_name  #a
}

![image](https://github.com/tone-row/flowchart-fun/assets/526758/1a2a2e54-5d55-40f8-a2a5-881bb0217a68)

**Comment by rob-gordon** [comment]
When containers are involved cytoscape (the underlying graphing library) sometimes gets state stuck in its cache. If you click the Bomb icon on the graph to refresh it, does it fix the problem?

**Comment by iotasquared** [comment]
it does not :/

**Comment by rob-gordon** [comment]
@iotasquared Thanks for opening this! It's a strange bug indeed. I'll get it fixed and let you know.

**Comment by rob-gordon** [comment]
@iotasquared Doh! I just realized the problem, sorry for not seeing it sooner.

`#Id's`, `.classes`, and `[data attributes]` always have to be in that order with no spaces (`#id.class[data]`) in between because they're read as one string of features. 

So when you begin your container with `.blue` the id after (`#abc`) is no longer valid. I think it seemed like it was working because the underlying regex has some room for error, but if you format it correctly then it doesn't matter how long or short the ID is.

```
A
  (#x)

Container #abcd.blue {
  B #x
}
```

Please let me know if you have any questions. I recognize it's a bit confusing.

**Comment by rob-gordon** [comment]
Closing. If you have other questions related to this you can open a new issue or ask in the [Discord](https://discord.gg/wPASTQHQBf)
