### ISSUE TITLE
Graph disappears after inserting a space before code line

### ISSUE THREAD

**Issue by hryb-michal** [tone-row/flowchart-fun#66]
To recreate:
- open new instance of app
- Add a single space on line 7, just before "lines have (...)"
- Refresh page (Ctrl+R) 
Chart vanishes.

I think storing chart state between separate sessions might be troublesome, but that's a topic for another discussion.

**Comment by rob-gordon** [comment]
There aren't many things that make the chart unable to render, but one of them is if you indent on the line below a "pointer" line (a line that uses `(pointer)`). Because you can't add a child to something that isn't a node in the first place.

I've probably made it as far as I can without adding any kind of validation feedback to users 😓

Thanks for flagging this!

**Comment by hryb-michal** [comment]
Perhaps it would make sense (if possible) to prevent user in general from entering more indents than the previous node has? I can't think of any use-case it could have impact on

**Comment by rob-gordon** [comment]
Going to close this as we now let the user know when the graph won't render because the text is invalid.
